// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config structure
 * Place the definition of custom battle configuration structure members in this file.
 *
 * Make sure that the name you want is not already taken by looking into battle.hpp
 * Do not forget to add initilization logic to battle_config_init.inc
 *
 * Format:
 *	 <datatype> name;
 **/

 int tier_1_max_monster_level;
 int tier_2_max_monster_level;
 int tier_3_max_monster_level;
 int tier_4_max_monster_level;
 int tier_5_max_monster_level;

 int core_orb_normal_id;
 int core_orb_normal_rate;
 int core_orb_rare_id;
 int core_orb_rare_rate;
 int core_orb_epic_id;
 int core_orb_epic_rate;
 int core_orb_mystical_id;
 int core_orb_mystical_rate;
 int core_orb_legendary_id;
 int core_orb_legendary_rate;
 
 int speciality_orb_normal_id;
 int speciality_orb_normal_rate;
 int speciality_orb_rare_id;
 int speciality_orb_rare_rate;
 int speciality_orb_epic_id;
 int speciality_orb_epic_rate;
 int speciality_orb_mystical_id;
 int speciality_orb_mystical_rate;
 int speciality_orb_legendary_id;
 int speciality_orb_legendary_rate;
 
 int gear_orb_normal_id;
 int gear_orb_normal_rate;
 int gear_orb_rare_id;
 int gear_orb_rare_rate;
 int gear_orb_epic_id;
 int gear_orb_epic_rate;
 int gear_orb_mystical_id;
 int gear_orb_mystical_rate;
 int gear_orb_legendary_id;
 int gear_orb_legendary_rate;
  
 int refine_orb_normal_id;
 int refine_orb_normal_rate;
 int refine_orb_rare_id;
 int refine_orb_rare_rate;
 int refine_orb_epic_id;
 int refine_orb_epic_rate;
 int refine_orb_mystical_id;
 int refine_orb_mystical_rate;
 int refine_orb_legendary_id;
 int refine_orb_legendary_rate;
