// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom battle config initializations
 * Place the definition of custom battle configuration initializations in this file.
 *
 * Do not forget to add a comma at the end of the line, if you want to add another config
 *
 * Format:
 *	 { "name", &battle_config.<variable name>, <default value>, <minimum value>, <maximum value> },
 **/

 { "tier_1_max_monster_level", &battle_config.tier_1_max_monster_level, 0, 0, INT_MAX, },
 { "tier_2_max_monster_level", &battle_config.tier_2_max_monster_level, 0, 0, INT_MAX, },
 { "tier_3_max_monster_level", &battle_config.tier_3_max_monster_level, 0, 0, INT_MAX, },
 { "tier_4_max_monster_level", &battle_config.tier_4_max_monster_level, 0, 0, INT_MAX, },
 { "tier_5_max_monster_level", &battle_config.tier_5_max_monster_level, 0, 0, INT_MAX, },

 { "core_orb_normal_id", &battle_config.core_orb_normal_id, 0, 0, INT_MAX, },
 { "core_orb_normal_rate", &battle_config.core_orb_normal_rate, 0, 0, INT_MAX, },
 { "core_orb_rare_id", &battle_config.core_orb_rare_id, 0, 0, INT_MAX, },
 { "core_orb_rare_rate", &battle_config.core_orb_rare_rate, 0, 0, INT_MAX, },
 { "core_orb_epic_id", &battle_config.core_orb_epic_id, 0, 0, INT_MAX, },
 { "core_orb_epic_rate", &battle_config.core_orb_epic_rate, 0, 0, INT_MAX, },
 { "core_orb_mystical_id", &battle_config.core_orb_mystical_id, 0, 0, INT_MAX, },
 { "core_orb_mystical_rate", &battle_config.core_orb_mystical_rate, 0, 0, INT_MAX, },
 { "core_orb_legendary_id", &battle_config.core_orb_legendary_id, 0, 0, INT_MAX, },
 { "core_orb_legendary_rate", &battle_config.core_orb_legendary_rate, 0, 0, INT_MAX, },
 
 { "speciality_orb_normal_id", &battle_config.speciality_orb_normal_id, 0, 0, INT_MAX, },
 { "speciality_orb_normal_rate", &battle_config.speciality_orb_normal_rate, 0, 0, INT_MAX, },
 { "speciality_orb_rare_id", &battle_config.speciality_orb_rare_id, 0, 0, INT_MAX, },
 { "speciality_orb_rare_rate", &battle_config.speciality_orb_rare_rate, 0, 0, INT_MAX, },
 { "speciality_orb_epic_id", &battle_config.speciality_orb_epic_id, 0, 0, INT_MAX, },
 { "speciality_orb_epic_rate", &battle_config.speciality_orb_epic_rate, 0, 0, INT_MAX, },
 { "speciality_orb_mystical_id", &battle_config.speciality_orb_mystical_id, 0, 0, INT_MAX, },
 { "speciality_orb_mystical_rate", &battle_config.speciality_orb_mystical_rate, 0, 0, INT_MAX, },
 { "speciality_orb_legendary_id", &battle_config.speciality_orb_legendary_id, 0, 0, INT_MAX, },
 { "speciality_orb_legendary_rate", &battle_config.speciality_orb_legendary_rate, 0, 0, INT_MAX, },
 
 { "gear_orb_normal_id", &battle_config.gear_orb_normal_id, 0, 0, INT_MAX, },
 { "gear_orb_normal_rate", &battle_config.gear_orb_normal_rate, 0, 0, INT_MAX, },
 { "gear_orb_rare_id", &battle_config.gear_orb_rare_id, 0, 0, INT_MAX, },
 { "gear_orb_rare_rate", &battle_config.gear_orb_rare_rate, 0, 0, INT_MAX, },
 { "gear_orb_epic_id", &battle_config.gear_orb_epic_id, 0, 0, INT_MAX, },
 { "gear_orb_epic_rate", &battle_config.gear_orb_epic_rate, 0, 0, INT_MAX, },
 { "gear_orb_mystical_id", &battle_config.gear_orb_mystical_id, 0, 0, INT_MAX, },
 { "gear_orb_mystical_rate", &battle_config.gear_orb_mystical_rate, 0, 0, INT_MAX, },
 { "gear_orb_legendary_id", &battle_config.gear_orb_legendary_id, 0, 0, INT_MAX, },
 { "gear_orb_legendary_rate", &battle_config.gear_orb_legendary_rate, 0, 0, INT_MAX, },
  
 { "refine_orb_normal_id", &battle_config.refine_orb_normal_id, 0, 0, INT_MAX, },
 { "refine_orb_normal_rate", &battle_config.refine_orb_normal_rate, 0, 0, INT_MAX, },
 { "refine_orb_rare_id", &battle_config.refine_orb_rare_id, 0, 0, INT_MAX, },
 { "refine_orb_rare_rate", &battle_config.refine_orb_rare_rate, 0, 0, INT_MAX, },
 { "refine_orb_epic_id", &battle_config.refine_orb_epic_id, 0, 0, INT_MAX, },
 { "refine_orb_epic_rate", &battle_config.refine_orb_epic_rate, 0, 0, INT_MAX, },
 { "refine_orb_mystical_id", &battle_config.refine_orb_mystical_id, 0, 0, INT_MAX, },
 { "refine_orb_mystical_rate", &battle_config.refine_orb_mystical_rate, 0, 0, INT_MAX, },
 { "refine_orb_legendary_id", &battle_config.refine_orb_legendary_id, 0, 0, INT_MAX, },
 { "refine_orb_legendary_rate", &battle_config.refine_orb_legendary_rate, 0, 0, INT_MAX, },
